FROM python:3.10.2-slim-buster
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    python -m venv venv && \
    venv/bin/pip install --upgrade pip && \
    venv/bin/pip install -r requirements.txt
COPY config.yaml .
COPY Data_processing.py .
COPY logger_info.py .
COPY main.py .
COPY scraper.py .
ENTRYPOINT [ "/app/venv/bin/python","/app/main.py" ]

